//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Infostandart")]
[assembly: AssemblyProduct("ODA")]
[assembly: AssemblyTrademark("www.infostandart.com")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("")]
[assembly: AssemblyKeyName("")]